/**
 * emit-draft-fill-sql.mjs — write the registry body into the empty DB shells.
 *
 * ─── WHAT THE EVIDENCE SHOWED (docs/db_evidence.csv, 2026-09-06 20:04) ──────
 * All nine "drafts" are 60–109 characters. They are title-only shells, not
 * unpublished articles:
 *
 *     109  kutai-yupa-borneo            88  scripts-that-sailed
 *      93  earth-sea-sangam             86  monsoon-trade-clock
 *      92  chola-naval-raid             81  stone-purana
 *      90  indian-ocean-power-networks  80  riders-on-monsoon
 *                                       60  geomythology-land-reclamation
 *
 * So the three plans on the table were all wrong:
 *   Master Plan Q2  "import 13"        -> would create 8 duplicate rows
 *   my earlier plan "publish 8"        -> would publish eight 90-character pages
 *   consolidate_02  gate en>=2000      -> correctly publishes ZERO of them
 *
 * The content for these articles exists, in the static TS registry. The row
 * exists, in the database. They have simply never been joined. The right
 * operation is neither INSERT nor a status flip: it is UPDATE the existing row
 * with the registry body, keeping its id, and publish only what is substantial.
 *
 * ─── WHY UPDATE AND NOT IMPORT ──────────────────────────────────────────────
 * The row id is referenced by srangam_article_pins, _versions, _analytics and
 * the correlation matrix. Importing a second row orphans all of that and is
 * exactly the duplication Master Plan Q3 exists to clean up. UPDATE preserves
 * every reference.
 *
 * ─── IDEMPOTENCE ────────────────────────────────────────────────────────────
 * Every emitted statement carries
 *     AND length(COALESCE(content::jsonb ->> 'en','')) < 200
 * so it fires only against a shell. Run the file twice and the second run
 * updates zero rows. If a body is later edited in the admin UI, this file can
 * never overwrite it.
 *
 * Placeholder languages are excluded (scripts/lib/substance.mjs) — only real
 * bodies are written, so no '[Professional Hindi translation required]' string
 * ever reaches the database.
 *
 *   node scripts/emit-draft-fill-sql.mjs > consolidate_02b_fill_shells.sql
 *
 * Reads only. Writes nothing to the database — it PRINTS SQL for you to review.
 */
import { build } from 'esbuild';
import { mkdirSync } from 'fs';
import { join } from 'path';
import { pathToFileURL } from 'url';
import { substantiveLangs, placeholderLangs } from './lib/substance.mjs';

const ROOT = process.cwd();
const TMPDIR = join(ROOT, 'node_modules', '.cache', 'registry-meta');
mkdirSync(TMPDIR, { recursive: true });

// The nine shells, and what the registry holds for each. Registry English
// lengths measured 2026-09-06; "hold" = the registry body is itself a card
// blurb and publishing it would put a sub-1000-character page on a public
// research site.
const SHELLS = {
  'stone-purana':                  { publish: true,  note: 'registry 38,844 chars' },
  'riders-on-monsoon':             { publish: true,  note: 'registry 9,210 chars' },
  'scripts-that-sailed':           { publish: true,  note: 'registry 7,181 chars (Part I; DB already has Part II separately)' },
  'earth-sea-sangam':              { publish: false, note: 'registry only 975 chars — a blurb; needs writing' },
  'monsoon-trade-clock':           { publish: false, note: 'registry only 913 chars — a blurb; needs writing' },
  'chola-naval-raid':              { publish: false, note: 'registry only 830 chars — a blurb; needs writing' },
  'indian-ocean-power-networks':   { publish: false, note: 'registry only 697 chars — a blurb; needs writing' },
  'kutai-yupa-borneo':             { publish: false, note: 'registry only 235 chars — a blurb; needs writing' },
  // geomythology-land-reclamation is deliberately ABSENT: the published row
  // geomythology-cultural-continuity (113,821 chars) IS this article. Its shell
  // is retired in consolidate_03, not filled.
};

await build({
  entryPoints: ['src/data/articles/index.ts'], bundle: true, format: 'esm',
  platform: 'node', outfile: join(TMPDIR, 'fill-bundle.mjs'),
  alias: { '@': ROOT + '/src' }, logLevel: 'error',
});
const { MULTILINGUAL_ARTICLES } = await import(pathToFileURL(join(TMPDIR, 'fill-bundle.mjs')));

const dollar = (s) => {
  // Dollar-quoting avoids every escaping question. Pick a tag the body cannot contain.
  let tag = 'body';
  let i = 0;
  while (s.includes(`$${tag}$`)) tag = `body${++i}`;
  return `$${tag}$${s}$${tag}$`;
};

const out = [];
out.push('-- consolidate_02b_fill_shells.sql');
out.push('-- GENERATED by scripts/emit-draft-fill-sql.mjs — do not hand-edit.');
out.push(`-- Generated ${new Date().toISOString()}`);
out.push('--');
out.push('-- All nine DB "drafts" are 60-109 character shells (docs/db_evidence.csv).');
out.push('-- This file writes the static registry body into the row that already exists,');
out.push('-- preserving its id and every foreign key that points at it. It never INSERTs.');
out.push('--');
out.push('-- Idempotent: each UPDATE is guarded by  en body < 200 chars,  so a second run');
out.push('-- changes nothing and an admin edit can never be overwritten.');
out.push('--');
out.push('-- Run the VERIFY block at the end BEFORE and AFTER. Wrap in BEGIN/COMMIT and');
out.push('-- read the RETURNING output before committing.');
out.push('');
out.push('BEGIN;');
out.push('');

let filled = 0, held = 0;
for (const [slug, cfg] of Object.entries(SHELLS)) {
  const art = MULTILINGUAL_ARTICLES.find((a) => a.id === slug);
  if (!art) { out.push(`-- MISSING FROM REGISTRY: ${slug} — skipped`); continue; }
  const langs = substantiveLangs(art.content);
  const stubs = placeholderLangs(art.content);
  const pairs = langs.map((l) => `'${l}', ${dollar(art.content[l])}`).join(',\n    ');
  out.push(`-- ── ${slug} ── ${cfg.note}`);
  out.push(`--    real languages: ${langs.join(',')}`
    + (stubs.length ? `   |   placeholders EXCLUDED: ${stubs.join(',')}` : ''));
  out.push(`--    ${cfg.publish ? 'PUBLISH after filling' : 'LEAVE AS DRAFT — body is a blurb, not an article'}`);
  out.push('UPDATE srangam_articles SET');
  out.push(`  content = jsonb_build_object(\n    ${pairs}\n  ),`);
  if (cfg.publish) {
    out.push("  status = 'published',");
    out.push('  published_date = COALESCE(published_date, CURRENT_DATE),');
  }
  out.push('  updated_at = now()');
  out.push(`WHERE slug = '${slug}'`);
  out.push("  AND length(COALESCE(content::jsonb ->> 'en','')) < 200   -- shell only; idempotent");
  out.push("RETURNING slug, status, length(content::jsonb ->> 'en') AS en_chars;");
  out.push('');
  cfg.publish ? filled++ : held++;
}

out.push('-- Review every RETURNING block above, then:  COMMIT;   (or ROLLBACK;)');
out.push('');
out.push('-- ═══ VERIFY — run before and after ═══════════════════════════════════════');
out.push("SELECT status, count(*), min(length(COALESCE(content::jsonb ->> 'en',''))) AS min_en,");
out.push("       max(length(COALESCE(content::jsonb ->> 'en',''))) AS max_en");
out.push('FROM srangam_articles GROUP BY status ORDER BY status;');
out.push('-- BEFORE: draft 9 rows, min_en 60, max_en 109');
out.push(`-- AFTER : published +${filled}, draft ${9 - filled} rows with real bodies`);
out.push('');
out.push('SELECT count(*) AS total FROM srangam_articles;   -- must still be 58, always');

console.log(out.join('\n'));
console.error(`emitted: ${filled} fill+publish, ${held} fill+hold, 1 excluded (geomythology shell -> consolidate_03)`);
