// Phase A0 (Accessibility plan 2026-07-19) — axe-core baseline scan.
// MEASUREMENT ONLY: this spec never fails on violations — it records them.
// It produces docs/a11y-baseline-<project>.md naming every offending node,
// which becomes the work order for Phases A1/A2 (including the root cause of
// PageSpeed's "Accessibility tree is not well-formed").
//
// Run: bun run test:e2e -- e2e/a11y.spec.ts   (or npx playwright test e2e/a11y.spec.ts)
// Requires: npm install -D @axe-core/playwright

import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import * as fs from 'node:fs';
import * as path from 'node:path';

const SLUG = process.env.E2E_ARTICLE_SLUG ?? 'reassessing-ashoka-legacy';

const PAGES: Array<{ label: string; url: string; waitFor?: string }> = [
  { label: 'home', url: '/' },
  { label: 'articles-index', url: '/articles' },
  { label: 'article', url: `/articles/${SLUG}`, waitFor: '[data-testid="article-body"]' },
  { label: 'search', url: '/search' },
];

type PageResult = {
  label: string;
  url: string;
  violations: Array<{
    id: string;
    impact: string | null | undefined;
    help: string;
    nodes: string[];
  }>;
};

const results: PageResult[] = [];

test.describe('Phase A0 — accessibility baseline (axe-core)', () => {
  for (const p of PAGES) {
    test(`axe scan: ${p.label}`, async ({ page }) => {
      await page.goto(p.url, { waitUntil: 'domcontentloaded' });
      if (p.waitFor) {
        await page.waitForSelector(p.waitFor, { state: 'visible', timeout: 20_000 });
      } else {
        await page.waitForLoadState('networkidle').catch(() => {});
      }

      const axe = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'best-practice'])
        .analyze();

      results.push({
        label: p.label,
        url: p.url,
        violations: axe.violations.map(v => ({
          id: v.id,
          impact: v.impact,
          help: v.help,
          nodes: v.nodes.slice(0, 10).map(n => n.target.join(' ')),
        })),
      });

      // Measurement-only: assert the scan RAN, not that it is clean.
      expect(axe).toBeTruthy();
      console.log(
        `[a11y] ${p.label}: ${axe.violations.length} violation rule(s) — ` +
        axe.violations.map(v => `${v.id}(${v.impact})×${v.nodes.length}`).join(', ')
      );
    });
  }

  test.afterAll(async ({ browserName: _browserName }, testInfo) => {
    const project = testInfo.project.name || 'default';
    const out = path.join('docs', `a11y-baseline-${project}.md`);
    const date = new Date().toISOString().slice(0, 10);

    let md = `# Accessibility baseline — ${project} (${date})\n\n`;
    md += `Generated by \`e2e/a11y.spec.ts\` (Phase A0). Tags: wcag2a, wcag2aa, best-practice.\n`;
    md += `Measurement only — violations recorded, not failed. Fix phases: A1/A2 in\n`;
    md += `docs/ACCESSIBILITY_AUDIT_AND_PLAN_2026-07-19.md\n\n`;

    let total = 0;
    for (const r of results) {
      md += `## ${r.label} (\`${r.url}\`) — ${r.violations.length} rule(s)\n\n`;
      if (r.violations.length === 0) {
        md += `✅ No violations found.\n\n`;
        continue;
      }
      for (const v of r.violations) {
        total += 1;
        md += `### \`${v.id}\` — impact: **${v.impact ?? 'n/a'}**\n${v.help}\n\n`;
        md += v.nodes.map(n => `- \`${n}\``).join('\n') + '\n\n';
      }
    }
    md += `---\nTotal violation rules across pages: ${total}\n`;

    fs.mkdirSync('docs', { recursive: true });
    fs.writeFileSync(out, md, 'utf8');
    console.log(`[a11y] baseline written → ${out}`);
  });
});
