import { CoverageMap } from './coverage';
import { SupportedLanguage } from '@/lib/i18n';

/**
 * Coverage data for Jambudvipa Connected article
 * This will be auto-generated by the translation pipeline
 */
export const jambudvipaConnectedCoverage: CoverageMap = {
  'jambudvipa-connected': {
    en: {
      slug: 'jambudvipa-connected',
      lang: 'en' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    ta: {
      slug: 'jambudvipa-connected',
      lang: 'ta' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    te: {
      slug: 'jambudvipa-connected',
      lang: 'te' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    kn: {
      slug: 'jambudvipa-connected',
      lang: 'kn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    bn: {
      slug: 'jambudvipa-connected',
      lang: 'bn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    as: {
      slug: 'jambudvipa-connected',
      lang: 'as' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    pn: {
      slug: 'jambudvipa-connected',
      lang: 'pn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    hi: {
      slug: 'jambudvipa-connected',
      lang: 'hi' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    pa: {
      slug: 'jambudvipa-connected',
      lang: 'pa' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    }
  }
};

/**
 * Get coverage for a specific article and language
 */
export function getArticleCoverage(slug: string, lang: SupportedLanguage) {
  return jambudvipaConnectedCoverage[slug]?.[lang];
}

/**
 * Get all coverage for an article
 */
export function getArticleCoverageMap(slug: string) {
  return jambudvipaConnectedCoverage[slug] || {};
}
