import { CoverageMap } from './coverage';
import { SupportedLanguage } from '@/lib/i18n';

/**
 * Coverage data for Jambudvipa Connected article
 * This will be auto-generated by the translation pipeline
 */
export const jambudvipaConnectedCoverage: CoverageMap = {
  'jambudvipa-connected': {
    en: {
      slug: 'jambudvipa-connected',
      lang: 'en' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    ta: {
      slug: 'jambudvipa-connected',
      lang: 'ta' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    te: {
      slug: 'jambudvipa-connected',
      lang: 'te' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    kn: {
      slug: 'jambudvipa-connected',
      lang: 'kn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    bn: {
      slug: 'jambudvipa-connected',
      lang: 'bn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    as: {
      slug: 'jambudvipa-connected',
      lang: 'as' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    pn: {
      slug: 'jambudvipa-connected',
      lang: 'pn' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    hi: {
      slug: 'jambudvipa-connected',
      lang: 'hi' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    },
    pa: {
      slug: 'jambudvipa-connected',
      lang: 'pa' as SupportedLanguage,
      percent: 100,
      totalKeys: 237,
      translatedKeys: 237,
      missingKeys: []
    }
  }
};

/**
 * Coverage data for Cosmic Island Sacred Land article
 */
export const cosmicIslandSacredLandCoverage: CoverageMap = {
  'cosmic-island-sacred-land': {
    en: {
      slug: 'cosmic-island-sacred-land',
      lang: 'en' as SupportedLanguage,
      percent: 100,
      totalKeys: 350,
      translatedKeys: 350,
      missingKeys: []
    },
    hi: {
      slug: 'cosmic-island-sacred-land',
      lang: 'hi' as SupportedLanguage,
      percent: 30,
      totalKeys: 350,
      translatedKeys: 105,
      missingKeys: []
    },
    ta: {
      slug: 'cosmic-island-sacred-land',
      lang: 'ta' as SupportedLanguage,
      percent: 30,
      totalKeys: 350,
      translatedKeys: 105,
      missingKeys: []
    },
    te: {
      slug: 'cosmic-island-sacred-land',
      lang: 'te' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    },
    kn: {
      slug: 'cosmic-island-sacred-land',
      lang: 'kn' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    },
    bn: {
      slug: 'cosmic-island-sacred-land',
      lang: 'bn' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    },
    as: {
      slug: 'cosmic-island-sacred-land',
      lang: 'as' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    },
    pa: {
      slug: 'cosmic-island-sacred-land',
      lang: 'pa' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    },
    pn: {
      slug: 'cosmic-island-sacred-land',
      lang: 'pn' as SupportedLanguage,
      percent: 0,
      totalKeys: 350,
      translatedKeys: 0,
      missingKeys: []
    }
  }
};

/**
 * Get coverage for a specific article and language
 */
export function getArticleCoverage(slug: string, lang: SupportedLanguage) {
  if (slug === 'jambudvipa-connected') {
    return jambudvipaConnectedCoverage[slug]?.[lang];
  }
  if (slug === 'cosmic-island-sacred-land') {
    return cosmicIslandSacredLandCoverage[slug]?.[lang];
  }
  return undefined;
}

/**
 * Get all coverage for an article
 */
export function getArticleCoverageMap(slug: string) {
  if (slug === 'jambudvipa-connected') {
    return jambudvipaConnectedCoverage[slug] || {};
  }
  if (slug === 'cosmic-island-sacred-land') {
    return cosmicIslandSacredLandCoverage[slug] || {};
  }
  return {};
}
