/**
 * Public project status. Every figure here was MEASURED, by a command.
 *
 * GENERATED by scripts/emit_project_status.py (STATUS_LIVE_2026_09_12). Do not hand-edit:
 * the numbers will drift and nobody will notice, which is exactly what
 * happened between 2026-09-08 and 2026-09-12, when this file reported a
 * corpus of 32,949 passages while the working database held 49,555. It was
 * reading the query_snapshot copy, not the live one. The difference was one
 * document - the Padma Purana Patala Khanda - ingested and never translated.
 *
 * To refresh:  python scripts/emit_project_status.py
 *
 * 2026-09-08 correction, kept because the reasoning still matters. An
 * earlier version carried `needsReview: 852`, described as passages at
 * contamination >= 0.15. That number was wrong. The threshold table in
 * scripts/diag_ocr_contamination.py summed pre-aggregated bands whose
 * boundaries are 0.00/0.02/0.05/0.10/0.20/0.35, selecting bands with
 * `lo >= thresh`. For thresh 0.15 the lowest qualifying band starts at 0.20,
 * so the row printed as "reject contamination >= 0.15" actually reported the
 * population at >= 0.20. Measured directly from per-passage values, the real
 * figure at >= 0.15 is 1,013.
 */
export const MEASURED_ON = "2026-09-12";

/**
 * The contamination figures below are NOT measured by the generator. They
 * come from diag_ocr_contamination.py in the automaton repository and carry
 * their own date, so that one heading cannot imply a freshness the numbers
 * underneath it do not have.
 */
export const CONTAMINATION_MEASURED_ON = "2026-09-08";

export const TRANSLATION_STATUS = {
  works: 60,
  passages: 49555,
  translated: 17013,
  /** Hindi verses in translations_l10n. Absent from this file until 2026-09-12. */
  translatedHi: 10036,
  completeWorks: [
    { name: "MBh01", passages: 6957, coverage: "100%" }
  ],
  entities: 6923,
  entityMentions: 28807,
  embeddings: 17032,
  /** Human fidelity reviews recorded. Not a sample size - a total. */
  humanReviews: 40,
  /**
   * Share of Devanagari-dominant passages scoring below 0.02 on the
   * Latin/scanner-intrusion measure. Whole corpus, not only the translated
   * part. Measured 2026-09-08.
   */
  cleanFraction: "58.6% below 0.02 contamination",
  /** Translated passages at >= 0.15 contamination. Measured 2026-09-08. */
  damagedTranslated: 1013,
  /** Of those, the share concentrated in a single work. */
  damagedConcentration: {
    work: "Bodhicaryāvatāra",
    passages: 703,
    share: "69%",
  },
} as const;

/**
 * Things the numbers above do not establish, stated because a research site
 * that reports only its wins is reporting half a result.
 */
export const CAVEATS = [
  {
    heading: "Half the corpus has not been touched",
    body:
      "17,013 of the 49,555 passages carry an English translation. The remainder is not spread thinly: 26,741 passages, 54.0% of the corpus, sit in 13 documents that are under 5% translated. The largest is SP 4214 Pataal Khanda from Padma Puran 1895 - Sri Venkateshwar Press - 16,606 passages, not one of them translated. A coverage figure quoted without that concentration would read as steady progress across the whole corpus, which is not what has happened.",
  },
  {
    heading: "Not one translation was refused",
    body:
      "Across all 17,013 translated passages, zero came back empty or as a refusal - including those drawn from badly damaged scans. An automated check for empty output therefore cannot tell us anything about them. Whether the model never declines, or declines are discarded before storage, has not yet been established.",
  },
  {
    heading: "The entity layer has never completed a pass",
    body:
      "The scheduled maintenance job that extracts named entities has started 41 times and finished zero times: it was re-processing every verse that had already returned no entities, on every run, and the task's one-hour limit killed it before it could record either a completion or an error. The entity and mention counts above are therefore a floor, not a total. Fixed 2026-09-12; the figures will rise.",
  },
] as const;

export const PANCHANG_STATUS = {
  engine: 'pyswisseph 2.10.03',
  zodiac: 'sidereal',
  tests: 137,
  /** How that figure is obtained: test function definitions counted by AST; pytest was not runnable. */
  testsMetric: "definitions",
  /** The point of the provenance work: the PDF reports the engine that ANSWERED. */
  provenance: 'measured at export time, not asserted',
  currentEphemeris: "Moshier analytic (Swiss .se1 files not installed)",
  /**
   * ephemeris_diff sizes what the Moshier fallback actually costs, in
   * arcseconds, in rasi/nakshatra/navamsa boundary crossings, and in days of
   * a 120-year Vimshottari cycle - and refuses the comparison outright when
   * both sides resolve to the same engine, which is the trap that makes a
   * fallback look free.
   */
  hasEphemerisDiff: true,
} as const;

export const NOT_YET = [
  'The Sanskrit corpus is not yet published to this site. Tables exist; nothing is loaded.',
  "Translation fidelity has been sampled but not yet read. A blinded 86-passage draw from the most damaged work is waiting on a human reader, and 40 reviews exist in total against 17,013 translated passages.",
] as const;
